site_name: Immunify Documentation
site_url: https://iseet26.github.io/immunify-docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - header.autohide

plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: false
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ar
          name: العربية
          build: true
        - locale: ku
          name: کوردی (سۆرانی)
          build: true

nav:
  - Home: index.md

extra:
  alternate:
    - name: English
      link: /immunify-docs/
      lang: en
    - name: العربية
      link: /immunify-docs/ar/
      lang: ar
    - name: کوردی (سۆرانی)
      link: /immunify-docs/ku/
      lang: ku

extra_css:
  - stylesheets/rtl.css

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
